### ISSUE TITLE
PATH issue with pytest 'ImportError: No module named  'moduleone'

### ISSUE THREAD

**Issue by LeMoussel** [idandaniel/ballyregan#12]
With `pytest` from the project root directory, the imports of local modules fail with  `E ModuleNotFoundError: No module named 'moduleone'`

**Solution:**
Recently, pytest (pytest>=7) has added a new core plugin that supports sys.path modifications via the [pythonpath configuration value](https://docs.pytest.org/en/7.1.x/reference/reference.html#confval-pythonpath). The solution is thus much simpler now and doesn't require any workarounds anymore with this in `pyproject.toml`
```
[tool.pytest.ini_options]
pythonpath = [
  "."
]
```

**Comment by idandaniel** [comment]
Hi, try using
python -m poetry run pytest
the 'python -m' should handle the PYTHONOPATH error.

Hope it helped!
