### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by wingsuiting** [idandaniel/ballyregan#26]
RuntimeError                              Traceback (most recent call last)
[<ipython-input-17-8f49073e23e4>](https://localhost:8080/#) in <cell line: 1>()
----> 1 proxy = fetcher.get_one()
      2 print(proxy)

4 frames
[/usr/lib/python3.10/asyncio/base_events.py](https://localhost:8080/#) in _check_running(self)
    582     def _check_running(self):
    583         if self.is_running():
--> 584             raise RuntimeError('This event loop is already running')
    585         if events._get_running_loop() is not None:
    586             raise RuntimeError(

RuntimeError: This event loop is already running

**Comment by idandaniel** [comment]
Can you give some more details?
Send your code it will help
