### ISSUE TITLE
Get proxy response time

### ISSUE THREAD

**Issue by LeMoussel** [idandaniel/ballyregan#6]
It would be interesting to have the response time (in milliseconds) for each proxy.
 Thus, we could obtain proxies by a filter on the maximum response time.
For example:
```python
proxies = fetcher.get(
  timeout=3000
)
print(proxies)
```

**Comment by idandaniel** [comment]
Good idea. The problem is that most providers does not supply that information, so by filtering by response time you will significantly reduce your results.
Let me think about it.
Thanks for the great idea though!

**Comment by LeMoussel** [comment]
[aiohttp docs](https://docs.aiohttp.org/en/stable/client_advanced.html#client-tracing) suggest to use [loop.time()](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.time) (which is also monotonic):

You can do something like this:
```python
        proxy = Proxy(
            protocol=Protocols.HTTPS,
            ip='127.0.0.1',
            port='8080',
            country='',
            anonymity=Anonymities.UNKNOWN,
        )
        judge_protocol = Protocols.HTTPS if proxy.protocol == Protocols.HTTPS else Protocols.HTTP
        async with aiohttp.ClientSession(
            timeout=ClientTimeout(total=30),
            connector=ProxyConnector.from_url(str(proxy))
        ) as session:
            try:
                start = asyncio.get_event_loop().time()
                async with session.get(f"{judge_protocol}://httpheader.net/azenv.php", ssl=False) as response:
                    response_time = asyncio.get_event_loop().time() - start
                    print(f'Proxy: {proxy} is valid, response time: {response_time:.4f} sec')
            except Exception:
                print(f'Proxy: {proxy} is invalid')
```
