### ISSUE TITLE
How to append own custom providers?

### ISSUE THREAD

**Issue by LeMoussel** [idandaniel/ballyregan#7]
I would like to develop and test other proxy providers.

You mention:
_You can write and append your own custom providers and pass it to the ProxyFetcher class as attribute.
Every custom proxy provider must implement the [IProxyProvider](https://github.com/idandaniel/ballyregan/blob/main/src/ballyregan/providers/interface.py) base interface._
```python
@dataclass
class TestProvider(IProxyProvider):
   def _get_raw_proxies(self,) -> List[Any]:
      # Do some stuff

   def raw_proxy_to_object(raw_proxy: Any) -> Proxy:
      # Do some stuff
```

I don't understand, how can I pass `TestProvider` to the ProxyFetcher class as attribute.
`fetcher = ProxyFetcher( ??? TestProvider ??? )`

**Comment by idandaniel** [comment]
right now, the _proxy_providers attribute is protected.
I will make it public and then you can just use it as a regular class attribute

**Comment by LeMoussel** [comment]
[aiohttp docs](https://docs.aiohttp.org/en/stable/client_advanced.html#client-tracing) suggest to use [loop.time()](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.time) (which is also monotonic):

You can do something like this:
```python
        proxy = Proxy(
            protocol=Protocols.HTTPS,
            ip='127.0.0.1',
            port='8080',
            country='',
            anonymity=Anonymities.UNKNOWN,
        )
        judge_protocol = Protocols.HTTPS if proxy.protocol == Protocols.HTTPS else Protocols.HTTP
        async with aiohttp.ClientSession(
            timeout=ClientTimeout(total=30),
            connector=ProxyConnector.from_url(str(proxy))
        ) as session:
            try:
                start = asyncio.get_event_loop().time()
                async with session.get(f"{judge_protocol}://httpheader.net/azenv.php", ssl=False) as response:
                    response_time = asyncio.get_event_loop().time() - start
                    print(f'Proxy: {proxy} is valid, response time: {response_time:.4f} sec')
            except Exception:
                print(f'Proxy: {proxy} is invalid')

```
